spring:
  profiles:
    active: dev
  application:
    name: carteira
  mvc:
    apiversion:
      use:
        path-segment: 1
      default: "v1"

server:
  port: 8082
springdoc:
  swagger-ui:
    path: /swagger-ui.html
