openapi: 3.1.0
info:
  title: "Cardapio"
  description: "Documentação do módulo cardapio da API"
  version: 0.1.0
servers:
  - url: 'http://localhost:8080'
paths:
  /itens:
    post:
      summary: "Cadastra um novo item"
      operationId: cadastrarItem
      responses:
        '201':
          description: "Item cadastrado com sucesso"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '400':
          description: "Dados inválidos"
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'

        '409':
          description: "Item existente"
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'

components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: long
        nome:
          type: string
        preco:
          type: bigDecimal
        disponivel:
          type: boolean

    ProblemDetail:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string